/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentActionPanel: typeof import('./src/components/AgentActionPanel.vue')['default']
    CaptureStatus: typeof import('./src/components/CaptureStatus.vue')['default']
    DevelopmentCaptureControl: typeof import('./src/components/DevelopmentCaptureControl.vue')['default']
    GreetComponent: typeof import('./src/components/GreetComponent.vue')['default']
    OutboundAccessControl: typeof import('./src/components/OutboundAccessControl.vue')['default']
    PrivacyStatus: typeof import('./src/components/PrivacyStatus.vue')['default']
    RecordingControl: typeof import('./src/components/RecordingControl.vue')['default']
    TimelinePanel: typeof import('./src/components/TimelinePanel.vue')['default']
  }
}
